exclude_paths:
  - vendor/*
  - tests/*
  - .tx/*
  - includes/libraries/* 
  - bin/*
  - assets/*
  - templates/*
  - ui/js/select2/*

engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
      
